### ISSUE TITLE
Related Things

### ISSUE THREAD

**Issue by iangilman** [karimkaylani/relatle#1]
I love this game! This isn't an issue, just some comments…

You might appreciate an app I've made which also allows you to explore related artists in an interesting way:

https://www.letsfathom.com/#/artist/Gorillaz

You might also appreciate this classic by @plamere:

http://boilthefrog.playlistmachinery.com/

**Comment by karimkaylani** [comment]
Thank you so much for the kind words! I'm really happy you're enjoying the game :) 

Your website was so much fun to mess around with, really awesome stuff! The boil the frog playlist maker was a ton of fun too. Please continue to send any similar stuff and suggestions :)
