### ISSUE TITLE
Audio Samples

### ISSUE THREAD

**Issue by iangilman** [karimkaylani/relatle#2]
Especially for artists you don't know, a nice educational/ hint mode would be for it to play samples of songs from the different artists (maybe when you click into them, or click an info button on the artist, or something). 

You can use the Spotify API for this and your users don't need to be logged in (as long as you just play samples).

**Comment by karimkaylani** [comment]
This is a great idea, thanks for the suggestion – I will start looking into this! Perhaps a speaker icon or a long press on the artist will play a sample of the song?

**Comment by karimkaylani** [comment]
This is now added! Long pressing on an artist card will play a 30sec preview of one of their top songs


https://github.com/karimkaylani/relatle/assets/19757304/5f87e0c0-b47b-4c85-bb43-02544b155988

**Comment by iangilman** [comment]
Awesome… This definitely makes the game less frustrating (but still challenging!)
