### ISSUE TITLE
End of Game Playlist

### ISSUE THREAD

**Issue by iangilman** [karimkaylani/relatle#3]
A fun feature at the end of the game, once you have created the chain, would be for it to produce a playlist with a song (most popular?) from each artist in the chain. 

There are probably a number of ways to accomplish this, but one option would be to save the playlist in the user's Spotify account (If they have one and connect it to your app). Another option with Spotify would be for you to make an account for Relatle, make the playlists there, and give out the links. Of course surely there are non-Spotify solutions as well, but it's the system I'm familiar with. 

I know this might not be the direction you want to go, but just thought I'd share the idea!

**Comment by karimkaylani** [comment]
Fantastic idea! Sadly I'm unable to properly integrate the Spotify API because of [their policy on not allowing games](https://developer.spotify.com/policy#iii-some-prohibited-applications) which is very disappointing. Would love any ideas on non-Spotify ways to accomplish this

**Comment by iangilman** [comment]
That's a weird policy… Disappointing.

I guess you could just spit out a playlist with track title and artist info and people could do with it what they will? Probably not much more useful than the artist list you already produce. 🤷‍♂️

While pondering this, I found a related Reddit thread from a few days ago and added some thoughts there:

https://www.reddit.com/r/makemeaplaylist/comments/1ghfqrn/is_there_a_playlist_sharing_file_format_designed/
